language: java
install: true

addons:
  sonarcloud:
    organization: "assertj"
    token:
      secure: "XS4jwdTTe2gkiXN6ssWvu/EG1de4d7AEdfC1JqwIeXy2qHluxvIDGtqi0RCsNZp/l5H+o1p39hIwutERMCL6MVmY0JVBePJkey43FCXNR+FmNBKuWR8mMOTL7Tq2kqVIs+Mxi495vW168hq/cjLi56GkH42DHGJmkS1TOOgxb2sJMWPF5CBGRWrwcz5DqVpiKBOOnGIys+SXybjXLMOeIpCzx30q3dPofSdp3Cj+bN+cWzG5yL7+iLqoJbFwtIuwkb5aGWISyVLrusrhCGLlA68+5lEBqhSO/htRqzBtC8tcoSm1KbCSgOkD0VChOpygzuEY4QTqBY9ZTjl0S1OVY9wuY3MIwBq1z1uNQ5pBUUUxLlykD5D3+i765GfFFBsGaOIJARn2ImuVV0AWrjzVPPY85eHTqbTmxr1lm3azAK0FHwn7eATyDruX5pvEZrmFJegT3u6IIQNwfUfmXJ9E+Up+T0Rh4yzu6YRDXKfZ2Wn95niTFgro4NbZ0WJ3umP0fvGp6esVBWOgwVYIea1VNxbQ5uhtYUSvb7m55udSQLUVmVlcLUX4IZhUs3NqiFl/srXymS+IKzBMqqYJ06eWx4IcIlvpcpzP5NtOS1Jl/wkzWD02IdYnTqXYRi7JJTtoqUDtsbRuM5ZFTwPilfNNgUu53pVab27v7cZOs13lLDE="
    branches:
      - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

git:
  depth: false

jdk:
  - openjdk11
  - openjdk13
  - openjdk14
  - openjdk-ea

matrix:
  allow_failures:
  - jdk: openjdk-ea

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./mvnw clean verify javadoc:javadoc; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./mvnw clean verify javadoc:javadoc sonar:sonar -Dsonar.projectKey=joel-costigliola_assertj-core; fi'
